name: System Check CI

on:
  push:
    branches: [ main ]

jobs:
  system-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run System Health Script
        run: bash scripts/system-check.sh
